linters:
  enable-all: true
  disable:
    - gomnd
    - gochecknoglobals
    - lll
    - funlen
    - wsl
    - gocognit
    - scopelint
    - gochecknoinits
    - unparam
    - interfacer
    - prealloc
  skip-dirs:
    - gen

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - goconst
