coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
    patch:
      default: off
flag_management:
  default_rules:
    statuses:
    - type: project
      target: 75%
    - type: patch
      target: 70%
  individual_flags:
  - name: cmd
    statuses:
    - type: project
      target: 60%
    - type: patch
      target: 60%
comment: off
