name: generate CREDITS
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
jobs:
  generate:
    if:  startsWith(github.head_ref, 'dependabot/') && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Generate token # required to trigger actions on the commit
      id: generate_token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      with:
        app_id: ${{ secrets.WRITE_APP_ID }}
        private_key: ${{ secrets.WRITE_PRIVATE_KEY }}
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ steps.generate_token.outputs.token }}
    - name: Install Go
      id: setup-go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: stable
        check-latest: true
        cache: false
    - uses: actions/cache/restore@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-ubuntu-latest-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-${{ steps.setup-go.outputs.go-version }}-
    - name: Generate CREDITS
      run: make credits
    - uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        add: CREDITS
        default_author: github_actions
        message: 'chore(deps): generate CREDITS'
